spring:
  profiles:
    active: ${spring.profiles.active}

management:
  endpoints:
    web:
      exposure:
        include: prometheus,metrics,health,info
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
